config/routes.rb
Rails.application.routes.draw do
  resources :translations
  resources :words
  resources :languages
  resources :englishes
  devise_for :users
  root 'home#index'
end

app/models/translation.rb
class Translation < ActiveRecord::Base
    #so that when a translation is deleted all its related englishes and languages are deleted
    has_many :englishes, dependent: :destroy
    has_many :languages, dependent: :destroy
    
    accepts_nested_attributes_for :englishes
    accepts_nested_attributes_for :languages
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]

  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = Translation.new
    @translation.englishes.build
    @translation.languages.build
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(translation_params)

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation, notice: 'Translation was successfully created.' }
        format.json { render :show, status: :created, location: @translation }
      else
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url, notice: 'Translation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id], languages_attributes: [ :id, :name, :word_id ], englishes_attributes: [ :id, :word, :meaning ])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params[:translation]
    end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= form_for(@translation) do |f| %>
  <% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
  <thead>
    <tr>
      <th>
        <%= f.fields_for :englishes do |english| %>
             <div class="field">
               <%= english.label :word %><br>
             </div>
          <% end %>
      </th><!-- english comes here -->
      
        <%# @languages.each do |language| %>  
          <th>
            <%= f.fields_for :languages do |language| %>
               <div class="field">
                 <%= language.label :name %><br>
               </div>
            <% end %>
          </th><!-- loop that brings all the new languages here -->
        <%# end %>
      
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>
          <%= f.fields_for :englishes do |english| %>
             <div class="field">
               <%= english.text_field :word %>
               <%#= f.select :english_id, English.all.map {|e| [e.word, e.id]} %>
             </div>
          <% end %>
        </td><!-- english comes here -->
        
        <%# @languages.each do |language| %>  
          <td>
            <%= f.fields_for :languages do |language| %>
               <div class="field">
                <%= language.text_field :name %>
               </div>
            <% end %>
          </td><!-- other languages.word.word come here -->
        <%# end %>
        
      </tr>
  </tbody>
</table>

  <div class="actions">
    <%= f.submit 'Submit Translation' %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing Translation</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Translations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @translations.each do |translation| %>
      <tr>
        <td><%= link_to 'Show', translation %></td>
        <td><%= link_to 'Edit', edit_translation_path(translation) %></td>
        <td><%= link_to 'Destroy', translation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Translation', new_translation_path %>

app/views/translations/new.html.erb
<h1>New Translation</h1>

<%= render 'form' %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>